import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const verseBlock = z.object({
  type: z.literal('verse'),
  number: z.number(),
  bo: z.array(z.string()), // one entry per poetic line; prose verses have length 1
  en: z.string(),
  cmn: z.string(), // Chinese (CUV) — no poetry line breaks in this source, plain string like en
  hi: z.string(), // Hindi (2017) — text only, no audio track
  ne: z.string(), // Nepali (ULB) — text only, no audio track
  paragraphStart: z.boolean(), // from the SFM's \p/\m markers — used by paragraph-layout mode
});

// Verse-start timestamps (seconds) for read-along highlighting. Amdo/Central/
// Kham are from John's forced-aligner export; English/Chinese were generated
// locally (Whisper transcription + text alignment — see CLAUDE.md). Null
// means that audio track's timing file hasn't arrived/been generated yet;
// the reading UI just skips highlighting then.
const timingTrack = z
  .array(z.object({ verse: z.number(), time: z.number() }))
  .nullable();

const chapters = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/chapters' }),
  schema: ({ image }) =>
    z.object({
      chapterNumber: z.number(),
      order: z.number(),
      labelBo: z.string(), // e.g. ལེའུ་དང་པོ། ("Chapter One")
      sectionTitleBo: z.string(),
      labelEn: z.string(), // e.g. "Chapter 1" — shown when text language is English
      sectionTitleEn: z.string(),
      labelCmn: z.string(), // e.g. "第一章" — shown when text language is Chinese
      sectionTitleCmn: z.string(),
      labelHi: z.string(), // e.g. "अध्याय 1" — shown when text language is Hindi
      sectionTitleHi: z.string(),
      labelNe: z.string(), // same label word as Hindi — shown when text language is Nepali
      sectionTitleNe: z.string(),
      cover: image(),
      verseCount: z.number(),
      audio: z.object({
        adx: z.string(), // Amdo
        bod: z.string(), // Central / Lhasa
        khg: z.string(), // Kham
        eng: z.string(), // English (BSB)
        cmn: z.string(), // Chinese (CUV, ElevenLabs)
      }),
      duration: z.object({
        adx: z.string(),
        bod: z.string(),
        khg: z.string(),
        eng: z.string(),
        cmn: z.string(),
      }),
      timing: z.object({
        adx: timingTrack,
        bod: timingTrack,
        khg: timingTrack,
        eng: timingTrack,
        cmn: timingTrack,
      }),
      blocks: z.array(
        z.discriminatedUnion('type', [
          verseBlock,
          z.object({ type: z.literal('image'), file: image() }),
        ]),
      ),
    }),
});

// Book introduction — Tibetan only, one entry (src/content/intro/ruth.json),
// generated by gen-chapters.mjs directly from 08RUTNTB.SFM's own front
// matter (\mt/\imt/\is1/\ipi, before the first \c). No audio, no
// per-language variants — see "Book introduction" in CLAUDE.md.
const intro = defineCollection({
  loader: glob({ pattern: '**/*.json', base: './src/content/intro' }),
  schema: z.object({
    mainTitle: z.string(), // \mt — the book's own title, shown as the modal's small label
    introTitle: z.string(), // \imt — the introduction's own (longer) title, shown as the modal's heading
    sections: z.array(
      z.object({
        heading: z.string(), // \is1
        paragraphs: z.array(z.string()), // \ipi, one per paragraph/outline line
      }),
    ),
  }),
});

export const collections = { chapters, intro };
